name: Push to Docker Hub
on: push

jobs:
  docker-hub-job:
    name: build and push
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: sean456
        password: dckr_pat_mwbKuUqLxCzlUObNYRJ52NLW33s
    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: sean456/test713:latest
